version: '3.8'
services:

  nextjs-wrapper:
    build:
      context: ./nextjs-wrapper
      dockerfile: Dockerfile.dev
    volumes:
      - ./nextjs-wrapper:/app
      - nextjs_node_modules:/app/node_modules
      - nextjs_next:/app/.next
    environment:
      - NODE_ENV=development
      - PORT=3002
    depends_on:
      - nginx-backend
    networks:
      - frontend

  react-app-dev:
    build:
      context: ./react_ws_src
      dockerfile: Dockerfile.dev
    volumes:
      - ./react_ws_src:/app
      - react_app_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    expose:
      - "3000"
    depends_on:
      - ws
    networks:
      - backend

  ws:
    build:
      context: ./WS
      dockerfile: Dockerfile
    volumes:
      - ./WS:/app
      - ws_node_modules:/app/node_modules
    expose:
      - "3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - backend

  nginx-backend:
    image: nginx:alpine
    expose:
      - "80"
    ports:
      - "8081:80" # debugging purpose
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react-app-dev
      - ws
    networks:
      - backend
      - frontend
      
  nginx-frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.frontend.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-wrapper
      - nginx-backend
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  react_app_node_modules:
  ws_node_modules:
  nextjs_node_modules:
  nextjs_next:
