version: '3.8'
services:

  react-app-prod:
    build:
      context: ./react_ws_src
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - ws
    deploy:
      replicas: 1

  ws:
    build:
      context: ./WS
      dockerfile: Dockerfile
    volumes:
      - ./WS:/app
      - ws_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001

      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react-app-prod
      - ws

volumes:
  react_app_node_modules:
  ws_node_modules:
