version: '3.8'
services:

  nextjs-wrapper:
    build:
      context: ./nextjs-wrapper
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3002
    depends_on:
      - nginx-backend
    networks:
      - frontend

  react-app-prod:
    build:
      context: ./react_ws_src
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      - ws
    deploy:
      replicas: 1
    networks:
      - backend

  ws:
    build:
      context: ./WS
      dockerfile: Dockerfile
    volumes:
      - ./WS:/app
      - ws_node_modules:/app/node_modules
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - backend

  nginx-backend:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react-app-prod
      - ws
    networks:
      - backend
      - frontend

  nginx-frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.frontend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-wrapper
      - nginx-backend
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  react_app_node_modules:
  ws_node_modules:
